title: Zheyi Xu
position: Staff Accountant
affiliation: Ernst and Young
email: ZheyiXu@my.uopeople.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/zheyixu99
linkedin: https://www.linkedin.cn/incareer/in/zheyixu
avatar: ./assets/img/profile photo-2.JPG
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon2.png
favicon_dark: ./assets/img/favicon.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
